---
# Provision vps with minimal configuration to use ansible

    - name: Change root password # only hash is supplied here
      user:
        name: root
        state: present
        password: "{{ root_password }}"

    - name: Add ansible group
      group:
        name: ansible
        state: present

    - name: Add ansible user to groups
      user: 
        name: ansible
        state: present
        create_home: yes
        groups: ansible
        append: yes # no removes the user from all other groups not listed in 'groups'
        password: "{{ ansible_password }}"

    - name: Add ansible user to sudoers 
      command: adduser ansible sudo

    - name: Set authorized ssh-keys for ansible user
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/{{ domain_name }}/id_ed25519.pub') }}" # lookups are executed on the control machine
        exclusive: True
        manage_dir: yes

    - name: Update the machine
      apt:
        update_cache: yes
        upgrade: safe
